### ISSUE TITLE
In the new build system how to link properly with libsodium?

### ISSUE THREAD

**Issue by vt-alt** [janmojzis/tinyssh#95]
When using
```
export CFLAGS="-I/usr/include/sodium"
export LDFLAGS="-lsodium"
```
Only `randombytes` is linked to libsodium but not other functions. Are there intended way to link with libsodium (which is libnacl compatible)?

Thanks,

**Comment by janmojzis** [comment]
I have to fix the faq, some things are obsolete (or will be obsolete) :(

DJB released new 'microlibraries':
- librandombytes: https://randombytes.cr.yp.to/
- lib25529: https://lib25519.cr.yp.to
- libntruprime: https://libntruprime.cr.yp.to

lib25519 covers x25519 and ed25519 and has very fast implementation on amd64/arm64, much faster then libsodium  currently has.
lib25519 also has very strict unit test and data-flow test https://lib25519.cr.yp.to/test.html


And have added suport for this microlibraries in current pre-relese `20241111`.
And also dropped support for other NaCl-compatible external libraries (As I wrote, I need to update the documentation better).

So if I can recommend, it is better to use with these new micro libraries.

**Comment by vt-alt** [comment]
Thanks for the answer. Yes I'm aware of there libs (even planned to build them for ALT). 

Can you clarify what will happen when these libraries are not present on the system? Will you maintain bundled versions of them?

**Comment by janmojzis** [comment]
All algorithms are now covered by internal libraries (and will be maintained in the future).
And linking with external libraries adds speed.
So tinyssh will work with or without external libraries same way, the difference will be in speed.

And now I am reworking the tests so that even the internal libraries are covered by the same tests as lib25519/libntruprime.
Including data-flow tests. Next release (assuming 20250101)  will contain them completely.

**Comment by vt-alt** [comment]
Thanks!
